;; redibuf - A project template generated by ahungry-fleece
;; Copyright (C) 2016 Your Name <redibuf@example.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; redibuf.lib.stub.lisp

(in-package #:cl-user)

(defpackage redibuf.lib.stub
  (:use :cl :redis)
  (:export
   :echo))

(in-package #:redibuf.lib.stub)

(defun ping ()
  (with-connection (:host "localhost" :port 6379)
    (red:set "ding" "dong")
    (print (red:get "food"))
    (print (red:get "ding"))
    (red:ping)))

(defun echo (input)
  input)

;;; "redibuf.lib.stub" goes here. Hacks and glory await!
